cluster_namespace: default
cluster_name: bench-cluster
num_coordinators: 36
namespaces:
- name: bench-10s:14d
  type: unaggregated
  retention: 336h
etcd_endpoints:
- http://etcd-0.etcd:2379
- http://etcd-1.etcd:2379
- http://etcd-2.etcd:2379
remote_coordinator_endpoints: []