apiVersion: apps/v1
kind: Deployment
metadata:
  name: promremotebench
spec:
  replicas: 10
  selector:
    matchLabels:
      k8s-app: promremotebench
  template:
    metadata:
      labels:
        k8s-app: promremotebench
    spec:
      containers:
      - name: promremotebench
        image: quay.io/m3db/promremotebench
        env:
        - name: PROMREMOTEBENCH_TARGET
          value: http://m3coordinator-bench-cluster:7201/api/v1/prom/remote/write
